### ISSUE TITLE
Jekyll maybe?

### ISSUE THREAD

**Issue by ghost** [alliswell/Less#14]
@alliswell I was just wondering If you would like to have a Jekyll version of this theme. I would personally like to, and I might be able to figure it, was just wondering if you would too?

**Comment by Japh** [comment]
I did this a while back... I might be able to dig it out for you. At least as a starting point.

**Comment by ghost** [comment]
+1 thanks man!

**Comment by Japh** [comment]
Sorry! As it turns out, I was thinking of the [Required](https://wordpress.org/themes/required) theme. My Jekyll repo for that is here: https://github.com/Japh/required-for-jekyll

I never converted Less.

**Comment by ghost** [comment]
ok sweet! I'm sure I can figure something out, using that as a baseline. Thanks!
