### ISSUE TITLE
Emoticons

### ISSUE THREAD

**Issue by mps** [alliswell/Less#5]
Right now they are not styled and appear massive.
![screen shot 2013-05-17 at 12 17 46 pm](https://f.cloud.github.com/assets/45475/519065/611fc874-bf0d-11e2-95f5-54cb50582229.png)

**Comment by alliswell** [comment]
thats because i have all images in the post going to the max width, simple fix would be to target the emoji's and "width:auto".. i'll make sure to do that in an update

**Comment by mps** [comment]
Sounds good. Thanks Jared
